#ifndef SynapseTopicsH
#define SynapseTopicsH

#ifdef __cplusplus
extern "C" {
#endif

// Physical (ROS to cerebri) (0-63)

#define SYNAPSE_IN_CMD_VEL_TOPIC 0
#define SYNAPSE_IN_CMD_VEL_TYPE Twist

#define SYNAPSE_IN_ODOMETRY_TOPIC 1
#define SYNAPSE_IN_ODOMETRY_TYPE Odometry

#define SYNAPSE_IN_JOY_TOPIC 2
#define SYNAPSE_IN_JOY_TYPE Joy

#define SYNAPSE_IN_BEZIER_TRAJECTORY_TOPIC 3
#define SYNAPSE_IN_BEZIER_TRAJECTORY_TYPE BezierTrajectory

#define SYNAPSE_IN_IMU_TOPIC 4
#define SYNAPSE_IN_IMU_TYPE IMU

#define SYNAPSE_IN_MAGNETIC_FIELD_TOPIC 5
#define SYNAPSE_IN_MAGNETIC_FIELD_TYPE MagneticField

#define SYNAPSE_IN_NAV_SAT_FIX_TOPIC 6
#define SYNAPSE_IN_NAV_SAT_FIX_TYPE NavSatFix

#define SYNAPSE_IN_ALTIMETER_TOPIC 7
#define SYNAPSE_IN_ALTIMETER_TYPE Altimeter

#define SYNAPSE_IN_ACTUATORS_TOPIC 8
#define SYNAPSE_IN_ACTUATORS_TYPE Actuators

#define SYNAPSE_IN_CLOCK_OFFSET_TOPIC 9
#define SYNAPSE_IN_CLOCK_OFFSET_TYPE Timestamp

#define SYNAPSE_IN_BATTERY_STATE_TOPIC 10
#define SYNAPSE_IN_BATTERY_STATE Timestamp

#define SYNAPSE_IN_WHEEL_ODOMETRY_TOPIC 11
#define SYNAPSE_IN_WHEEL_ODOMETRY_TYPE WheelOdometry

#define SYNAPSE_IN_SIM_CLOCK_TOPIC 63
#define SYNAPSE_IN_SIM_CLOCK_TYPE SimClock

// Physical/Simulation (cerebri to ROS) (64-127)

#define SYNAPSE_OUT_CMD_VEL_TOPIC 64
#define SYNAPSE_OUT_CMD_VEL_TYPE Twist

#define SYNAPSE_OUT_ODOMETRY_TOPIC 65
#define SYNAPSE_OUT_ODOMETRY_TYPE Odometry

#define SYNAPSE_OUT_JOY_TOPIC 66
#define SYNAPSE_OUT_JOY_TYPE Joy

#define SYNAPSE_OUT_BEZIER_TRAJECTORY_TOPIC 67
#define SYNAPSE_OUT_BEZIER_TRAJECTORY_TYPE BezierTrajectory

#define SYNAPSE_OUT_IMU_TOPIC 68
#define SYNAPSE_OUT_IMU_TYPE IMU

#define SYNAPSE_OUT_MAGNETIC_FIELD_TOPIC 69
#define SYNAPSE_OUT_MAGNETIC_FIELD_TYPE MagneticField

#define SYNAPSE_OUT_NAV_SAT_FIX_TOPIC 70
#define SYNAPSE_OUT_NAV_SAT_FIX_TYPE NavSatFix

#define SYNAPSE_OUT_ALT_TOPIC 71
#define SYNAPSE_OUT_ALT_TYPE Altimeter

#define SYNAPSE_OUT_ACTUATORS_TOPIC 72
#define SYNAPSE_OUT_ACTUATORS_TYPE Actuators

#define SYNAPSE_OUT_CLOCK_OFFSET_TOPIC 73
#define SYNAPSE_OUT_CLOCK_OFFSET_TYPE Timestamp

#define SYNAPSE_OUT_BATTERY_STATE_TOPIC 74
#define SYNAPSE_OUT_BATTERY_STATE BatteryState

#define SYNAPSE_OUT_WHEEL_ODOMETRY_TOPIC 75
#define SYNAPSE_OUT_WHEEL_ODOMETRY_TYPE WheelOdometry

// Reserved (128-255)

#ifdef __cplusplus
}
#endif

#endif //SynapseTopicsH
